name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/deploy-docs.yml'
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy README for 11ty
        run: |
          # Copy README.md to the src directory for 11ty
          cp README.md docs/src/
      
      - name: Install dependencies and build
        run: |
          cd docs
          npm install
          npx @11ty/eleventy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/dist
          branch: gh-pages