name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/deploy-docs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Docsify CLI
        run: npm install -g docsify-cli
      
      - name: Setup Documentation Structure
        run: |
          mkdir -p docs
          cp README.md docs/README.md
          
          # Create index.html
          cat > docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>URLTracker Documentation</title>
            <meta name="description" content="Documentation for URLTracker">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
          </head>
          <body>
            <div id="app"></div>
            <script>
              window.$docsify = {
                name: 'URLTracker',
                repo: 'https://github.com/nalmeida/urltracker',
                auto2top: true,
                coverpage: false,
                loadSidebar: false,
                subMaxLevel: 2,
              };
            </script>
            <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-javascript.min.js"></script>
          </body>
          </html>
          EOL
          
          # Create .nojekyll file to prevent Jekyll processing
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages